import React, { useState, useEffect } from 'react';
import { Plus, Search, MapPin, Hash, Printer as PrinterIcon, Edit2, X, Wifi, Usb, Globe, Trash2, History, Truck, AlertTriangle, QrCode, FileSpreadsheet, Download, CheckCircle2, XCircle, AlertCircle, Archive, RefreshCw } from 'lucide-react';
import { Printer, SystemConfig, StockLog, ServiceRecord, PrinterStatus } from '../types';
import { StorageService } from '../services/storage';

interface PrinterListProps {
  onSelectPrinter?: (printer: Printer) => void;
  targetPrinterId?: string | null;
  clearTarget?: () => void;
}

export const PrinterList: React.FC<PrinterListProps> = ({ onSelectPrinter, targetPrinterId, clearTarget }) => {
  const [printers, setPrinters] = useState<Printer[]>([]);
  const [config, setConfig] = useState<SystemConfig>({ brands: [], models: [], suppliers: [], tonerModels: [] });
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);
  
  // Modals State
  const [isFormModalOpen, setIsFormModalOpen] = useState(false);
  const [isHistoryModalOpen, setIsHistoryModalOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  
  // QR Code Modal
  const [qrPrinter, setQrPrinter] = useState<Printer | null>(null);

  const [editingPrinter, setEditingPrinter] = useState<Printer | null>(null);
  const [selectedPrinterHistory, setSelectedPrinterHistory] = useState<{printer: Printer, tonerLogs: StockLog[], serviceLogs: ServiceRecord[]} | null>(null);

  // Form State
  const [formData, setFormData] = useState<Partial<Printer>>({
    brand: '',
    model: '',
    serialNumber: '',
    location: '',
    floor: '',
    lastCounter: 0,
    compatibleToner: '',
    connectionType: 'USB',
    ipAddress: '',
    supplier: '',
    status: 'ACTIVE'
  });

  useEffect(() => {
    loadData();
  }, []);

  // Deep Linking Logic
  useEffect(() => {
    if (targetPrinterId && printers.length > 0) {
      const target = printers.find(p => p.id === targetPrinterId);
      if (target) {
        openHistoryModal(target);
      }
      if (clearTarget) clearTarget();
    }
  }, [targetPrinterId, printers]);

  const loadData = async () => {
    setLoading(true);
    const [p, c] = await Promise.all([
      StorageService.getPrinters(),
      StorageService.getConfig()
    ]);
    setPrinters(p);
    setConfig(c);
    setLoading(false);
  };

  // --- ACTIONS ---

  const confirmDelete = (e: React.MouseEvent, id: string) => {
    e.preventDefault();
    e.stopPropagation();
    setDeleteId(id);
  };

  const performDelete = async () => {
    if (deleteId) {
      await StorageService.deletePrinter(deleteId);
      setDeleteId(null);
      loadData(); // Reload list
    }
  };

  const handleEditClick = (e: React.MouseEvent, printer: Printer) => {
    e.preventDefault();
    e.stopPropagation();
    openFormModal(printer);
  };

  const handleQrClick = (e: React.MouseEvent, printer: Printer) => {
    e.preventDefault();
    e.stopPropagation();
    setQrPrinter(printer);
  };

  const handleHistoryClick = (printer: Printer) => {
    openHistoryModal(printer);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (editingPrinter && editingPrinter.id) {
       // Update
       const updatedPrinter = { ...editingPrinter, ...formData } as Printer;
       await StorageService.updatePrinter(updatedPrinter);
    } else {
       // Create
       const newPrinter: Printer = {
        id: '', // Generated by Firestore
        lastTonerDate: new Date().toISOString(),
        ...formData as Printer,
        status: formData.status || 'ACTIVE'
       };
       await StorageService.addPrinter(newPrinter);
    }

    closeFormModal();
    loadData(); // Reload list from DB
  };

  const downloadInventoryCSV = () => {
    if (printers.length === 0) {
      alert('İndirilecek veri yok.');
      return;
    }

    const headers = ["Marka", "Model", "Seri No", "Konum", "Kat", "Son Sayaç", "Toner", "IP", "Durum", "Tedarikçi"];
    
    const rows = printers.map(p => {
        const clean = (val: any) => `"${String(val || '').replace(/"/g, '""')}"`;
        return [
            clean(p.brand),
            clean(p.model),
            clean(p.serialNumber),
            clean(p.location),
            clean(p.floor),
            clean(p.lastCounter),
            clean(p.compatibleToner),
            clean(p.ipAddress || 'USB'),
            clean(p.status),
            clean(p.supplier)
        ].join(",");
    });

    const csvContent = "data:text/csv;charset=utf-8,\uFEFF" + headers.join(",") + "\n" + rows.join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `yazici_envanter_${new Date().toLocaleDateString()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- MODAL HELPERS ---

  const openFormModal = (printer?: Printer) => {
    if (printer) {
      setEditingPrinter(printer);
      setFormData(printer);
    } else {
      setEditingPrinter(null);
      setFormData({
        brand: config.brands[0] || '',
        model: config.models[0] || '',
        serialNumber: '',
        location: '',
        floor: '',
        lastCounter: 0,
        compatibleToner: '',
        connectionType: 'USB',
        ipAddress: '',
        supplier: config.suppliers[0] || '',
        status: 'ACTIVE'
      });
    }
    setIsFormModalOpen(true);
  };

  const closeFormModal = () => {
    setIsFormModalOpen(false);
    setEditingPrinter(null);
  };

  const openHistoryModal = async (printer: Printer) => {
    // Fetch fresh logs for this specific history view
    const allLogs = await StorageService.getLogs();
    const allServices = await StorageService.getServiceRecords();

    const printerLogs = allLogs.filter(log => String(log.printerId) === String(printer.id)).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const printerServices = allServices.filter(srv => String(srv.printerId) === String(printer.id)).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    setSelectedPrinterHistory({
      printer,
      tonerLogs: printerLogs,
      serviceLogs: printerServices
    });
    setIsHistoryModalOpen(true);
  };

  const filteredPrinters = printers.filter(p => 
    p.model.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.brand.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.serialNumber.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // ... (Status Helpers remain the same) ...
  const getStatusColor = (status: PrinterStatus) => {
    switch (status) {
      case 'ACTIVE': return 'border-emerald-500 bg-emerald-50 dark:bg-emerald-900/10 dark:border-emerald-500/50';
      case 'SPARE': return 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/10 dark:border-indigo-500/50';
      case 'MAINTENANCE': return 'border-orange-500 bg-orange-50 dark:bg-orange-900/10 dark:border-orange-500/50';
      case 'BROKEN': return 'border-red-500 bg-red-50 dark:bg-red-900/10 dark:border-red-500/50';
      case 'SCRAPPED': return 'border-slate-500 bg-slate-100 dark:bg-slate-800 dark:border-slate-500 opacity-75';
      default: return 'border-slate-200';
    }
  };

  const getStatusLabel = (status: PrinterStatus) => {
    switch (status) {
      case 'ACTIVE': return { text: 'AKTİF', icon: <CheckCircle2 size={12} /> };
      case 'SPARE': return { text: 'YEDEKTE', icon: <Archive size={12} /> };
      case 'MAINTENANCE': return { text: 'SERVİSTE', icon: <Truck size={12} /> };
      case 'BROKEN': return { text: 'ARIZALI', icon: <AlertTriangle size={12} /> };
      case 'SCRAPPED': return { text: 'HURDA', icon: <XCircle size={12} /> };
      default: return { text: 'BİLİNMİYOR', icon: null };
    }
  };

  if (loading) {
     return <div className="flex justify-center items-center h-64 text-slate-500">Yazıcılar yükleniyor...</div>;
  }

  return (
    <div className="space-y-6 pb-24">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white dark:bg-slate-800 p-4 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">Cihaz Yönetimi</h2>
          <p className="text-sm text-slate-500 dark:text-slate-400">Toplam {printers.length} yazıcı listeleniyor</p>
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
             <button onClick={loadData} className="p-3 bg-slate-100 dark:bg-slate-700 rounded-xl text-slate-600 dark:text-slate-300 hover:bg-slate-200"><RefreshCw size={20}/></button>
            <button 
            onClick={downloadInventoryCSV}
            className="flex-1 sm:flex-none bg-green-600 hover:bg-green-700 text-white px-4 py-3 rounded-xl flex items-center justify-center gap-2 font-semibold shadow-sm transition-all"
            >
            <FileSpreadsheet size={20} /> Excel
            </button>
            <button 
            onClick={() => openFormModal()}
            className="flex-[2] sm:flex-none bg-primary-600 hover:bg-primary-700 text-white px-5 py-3 rounded-xl flex items-center justify-center gap-2 font-semibold shadow-lg shadow-primary-200 dark:shadow-none transition-all active:scale-95"
            >
            <Plus size={20} />
            Yeni Cihaz
            </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative group">
        <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
          <Search className="text-slate-400 group-focus-within:text-primary-500 transition-colors" size={20} />
        </div>
        <input
          type="text"
          placeholder="Marka, Model, Seri No veya Konum ara..."
          className="w-full pl-11 pr-4 py-4 rounded-2xl border-2 border-transparent bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm focus:border-primary-500 focus:ring-0 outline-none transition-all placeholder:text-slate-400"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      {/* CARD GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {filteredPrinters.map(printer => {
          const statusInfo = getStatusLabel(printer.status || 'ACTIVE');
          const cardStyle = getStatusColor(printer.status || 'ACTIVE');

          return (
            <div 
              key={printer.id} 
              className={`group bg-white dark:bg-slate-800 rounded-2xl shadow-sm hover:shadow-xl border-2 overflow-hidden transition-all duration-300 flex flex-col relative ${cardStyle}`}
            >
              {/* QR CODE BUTTON - ABSOLUTE TOP RIGHT */}
              <button 
                  onClick={(e) => handleQrClick(e, printer)}
                  className="absolute top-4 right-4 p-2 bg-white/80 dark:bg-slate-700/80 backdrop-blur-sm text-slate-600 dark:text-slate-300 rounded-lg shadow-sm hover:text-primary-600 dark:hover:text-primary-400 z-10"
                  title="QR Kod Göster"
              >
                  <QrCode size={20} />
              </button>

              {/* CARD BODY */}
              <div 
                className="p-5 flex-1 cursor-pointer relative"
                onClick={() => handleHistoryClick(printer)}
              >
                {/* Brand & Status Badge */}
                <div className="flex justify-between items-start mb-4 pr-10">
                    <div className="flex flex-col gap-2">
                        <span className="bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 px-3 py-1 rounded-lg text-xs font-bold uppercase tracking-wider w-fit">
                          {printer.brand}
                        </span>
                        <span className={`flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase w-fit tracking-wide
                          ${printer.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300' : ''}
                          ${printer.status === 'SPARE' ? 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900 dark:text-indigo-300' : ''}
                          ${printer.status === 'MAINTENANCE' ? 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300' : ''}
                          ${printer.status === 'BROKEN' ? 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300' : ''}
                          ${printer.status === 'SCRAPPED' ? 'bg-slate-200 text-slate-600 dark:bg-slate-700 dark:text-slate-400' : ''}
                        `}>
                           {statusInfo.icon} {statusInfo.text}
                        </span>
                    </div>
                </div>

                {/* Model Name */}
                <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-1 group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">
                  {printer.model}
                </h3>
                
                {/* Location & Serial */}
                <div className="space-y-2 mt-4">
                    <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 text-sm">
                      <MapPin size={16} className="text-slate-400" />
                      <span className="line-clamp-1">{printer.location} <span className="text-slate-400">({printer.floor})</span></span>
                    </div>
                    <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 text-sm">
                      <Hash size={16} className="text-slate-400" />
                      <span className="font-mono">{printer.serialNumber}</span>
                    </div>
                    <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400 text-sm">
                      {printer.connectionType === 'Network' ? <Globe size={16} className="text-emerald-500"/> : <Usb size={16} className="text-slate-400"/>}
                      <span className="font-mono text-xs">{printer.connectionType === 'Network' ? printer.ipAddress : 'USB Bağlantı'}</span>
                    </div>
                </div>
              </div>

              {/* ACTION FOOTER */}
              <div className="grid grid-cols-2 border-t border-slate-200 dark:border-slate-700 divide-x divide-slate-200 dark:divide-slate-700">
                <button 
                    onClick={(e) => handleEditClick(e, printer)}
                    className="py-4 flex items-center justify-center gap-2 text-blue-600 dark:text-blue-400 font-semibold hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors active:bg-blue-100"
                >
                    <Edit2 size={18} /> Düzenle
                </button>
                <button 
                    onClick={(e) => confirmDelete(e, printer.id)}
                    className="py-4 flex items-center justify-center gap-2 text-red-600 dark:text-red-400 font-semibold hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors active:bg-red-100"
                >
                    <Trash2 size={18} /> Sil
                </button>
              </div>
            </div>
          );
        })}

        {printers.length === 0 && (
           <div className="col-span-full flex flex-col items-center justify-center py-20 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border-2 border-dashed border-slate-200 dark:border-slate-700">
              <PrinterIcon size={48} className="text-slate-300 mb-4" />
              <p className="text-slate-500 font-medium">Kayıtlı yazıcı bulunamadı</p>
              <p className="text-slate-400 text-sm">Yeni eklemek için butonu kullanın</p>
           </div>
        )}
      </div>

      {/* --- QR CODE MODAL --- */}
      {qrPrinter && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-[70] flex items-center justify-center p-4 animate-in fade-in duration-200" onClick={() => setQrPrinter(null)}>
            <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-2xl max-w-sm w-full text-center relative" onClick={e => e.stopPropagation()}>
                <button onClick={() => setQrPrinter(null)} className="absolute top-4 right-4 p-2 bg-slate-100 dark:bg-slate-700 rounded-full text-slate-500"><X size={20}/></button>
                
                <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-1">{qrPrinter.brand} {qrPrinter.model}</h3>
                <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">{qrPrinter.location}</p>
                
                <div className="bg-white p-4 rounded-xl border-2 border-slate-100 inline-block mb-4">
                    <img 
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(window.location.origin + window.location.pathname + '?pid=' + qrPrinter.id)}`} 
                        alt="QR Code" 
                        className="w-48 h-48"
                    />
                </div>
                
                <p className="text-xs text-slate-400 max-w-[250px] mx-auto">
                    Bu kodu yazıcının üzerine yapıştırın. Telefondan okutulduğunda direkt bu sayfa açılacaktır.
                </p>
            </div>
        </div>
      )}

      {/* --- DELETE MODAL --- */}
      {deleteId && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[60] flex items-center justify-center p-4 animate-in fade-in duration-200">
           <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-sm w-full p-6 text-center scale-100 animate-in zoom-in-95 duration-200">
              <div className="w-16 h-16 bg-red-100 dark:bg-red-900/30 text-red-600 rounded-full flex items-center justify-center mx-auto mb-4">
                 <Trash2 size={32} />
              </div>
              <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-2">Yazıcı Siliniyor</h3>
              <p className="text-slate-500 dark:text-slate-400 text-sm mb-6">
                 Bu cihazı ve geçmiş tüm kayıtlarını kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.
              </p>
              <div className="grid grid-cols-2 gap-3">
                 <button 
                    onClick={() => setDeleteId(null)}
                    className="py-3 px-4 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl font-semibold hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors"
                 >
                    Vazgeç
                 </button>
                 <button 
                    onClick={performDelete}
                    className="py-3 px-4 bg-red-600 text-white rounded-xl font-semibold hover:bg-red-700 shadow-lg shadow-red-200 dark:shadow-none transition-colors"
                 >
                    Evet, Sil
                 </button>
              </div>
           </div>
        </div>
      )}

      {/* Add/Edit Modal */}
      {isFormModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-800 rounded-2xl w-full max-w-lg shadow-2xl overflow-y-auto max-h-[90vh] animate-in slide-in-from-bottom-4 duration-300">
            <div className="bg-white dark:bg-slate-800 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center sticky top-0 z-10">
              <h3 className="font-bold text-lg text-slate-800 dark:text-white">
                {editingPrinter ? 'Cihazı Düzenle' : 'Yeni Cihaz Ekle'}
              </h3>
              <button type="button" onClick={closeFormModal} className="p-2 bg-slate-100 dark:bg-slate-700 rounded-full hover:bg-slate-200 transition-colors"><X size={20} className="text-slate-500 dark:text-slate-300" /></button>
            </div>
            
            <form onSubmit={handleSave} className="p-6 space-y-5">
              
              {/* STATUS SELECTION (NEW) */}
              <div className="bg-slate-50 dark:bg-slate-700/50 p-4 rounded-xl border border-slate-100 dark:border-slate-700">
                 <label className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-3">Cihaz Durumu</label>
                 <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                    {[
                      { val: 'ACTIVE', label: 'Aktif', color: 'bg-emerald-100 text-emerald-700 border-emerald-300' },
                      { val: 'SPARE', label: 'Yedek', color: 'bg-indigo-100 text-indigo-700 border-indigo-300' },
                      { val: 'MAINTENANCE', label: 'Serviste', color: 'bg-orange-100 text-orange-700 border-orange-300' },
                      { val: 'BROKEN', label: 'Arızalı', color: 'bg-red-100 text-red-700 border-red-300' },
                      { val: 'SCRAPPED', label: 'Hurda', color: 'bg-slate-200 text-slate-700 border-slate-300' }
                    ].map(opt => (
                       <label key={opt.val} className={`cursor-pointer border-2 rounded-lg p-2 text-center text-xs font-bold transition-all ${
                          formData.status === opt.val ? opt.color : 'border-slate-200 text-slate-500 bg-white dark:bg-slate-800 dark:border-slate-600'
                       }`}>
                          <input type="radio" className="hidden" name="status" checked={formData.status === opt.val} onChange={() => setFormData({...formData, status: opt.val as PrinterStatus})} />
                          {opt.label}
                       </label>
                    ))}
                 </div>
              </div>

              {/* Brand & Model Select */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Marka</label>
                  <div className="relative">
                     <select 
                        required 
                        className="w-full appearance-none p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white transition-all"
                        value={formData.brand} 
                        onChange={e => setFormData({...formData, brand: e.target.value})}
                     >
                        <option value="">Seçiniz</option>
                        {config.brands.map(b => <option key={b} value={b}>{b}</option>)}
                     </select>
                     <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">▼</div>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Model</label>
                  <div className="relative">
                     <select 
                        required 
                        className="w-full appearance-none p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white transition-all"
                        value={formData.model} 
                        onChange={e => setFormData({...formData, model: e.target.value})}
                     >
                        <option value="">Seçiniz</option>
                        {config.models.map(m => <option key={m} value={m}>{m}</option>)}
                     </select>
                     <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">▼</div>
                  </div>
                </div>
              </div>

              {/* Supplier Selection */}
              <div>
                 <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Tedarikçi / Servis</label>
                 <div className="relative">
                     <select 
                        className="w-full appearance-none p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white transition-all"
                        value={formData.supplier} 
                        onChange={e => setFormData({...formData, supplier: e.target.value})}
                     >
                        <option value="">Seçiniz</option>
                        {config.suppliers.map(s => <option key={s} value={s}>{s}</option>)}
                     </select>
                     <Truck size={18} className="absolute right-10 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
                     <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">▼</div>
                  </div>
              </div>

              {/* Connection Type */}
              <div className="bg-slate-50 dark:bg-slate-700/50 p-4 rounded-xl border border-slate-100 dark:border-slate-700">
                <label className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-3">Bağlantı Türü</label>
                <div className="flex gap-4 mb-4">
                  <label className={`flex-1 flex items-center justify-center gap-2 cursor-pointer p-3 rounded-lg border transition-all ${formData.connectionType === 'USB' ? 'bg-white dark:bg-slate-600 border-primary-500 shadow-sm text-primary-700 dark:text-primary-300' : 'border-transparent hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-500'}`}>
                    <input 
                      type="radio" 
                      name="connType" 
                      className="hidden"
                      checked={formData.connectionType === 'USB'} 
                      onChange={() => setFormData({...formData, connectionType: 'USB', ipAddress: ''})} 
                    />
                    <Usb size={18}/> USB
                  </label>
                  <label className={`flex-1 flex items-center justify-center gap-2 cursor-pointer p-3 rounded-lg border transition-all ${formData.connectionType === 'Network' ? 'bg-white dark:bg-slate-600 border-primary-500 shadow-sm text-primary-700 dark:text-primary-300' : 'border-transparent hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-500'}`}>
                    <input 
                      type="radio" 
                      name="connType" 
                      className="hidden"
                      checked={formData.connectionType === 'Network'} 
                      onChange={() => setFormData({...formData, connectionType: 'Network'})} 
                    />
                    <Wifi size={18}/> Network
                  </label>
                </div>
                
                {formData.connectionType === 'Network' && (
                  <div>
                    <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 mb-1 uppercase tracking-wider">IP Adresi</label>
                    <div className="relative">
                      <Globe size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                      <input 
                        type="text" 
                        required 
                        className="w-full pl-10 p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-white dark:bg-slate-600 text-slate-900 dark:text-white font-mono"
                        value={formData.ipAddress} 
                        onChange={e => setFormData({...formData, ipAddress: e.target.value})} 
                        placeholder="192.168.1.xxx" 
                      />
                    </div>
                  </div>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Seri No</label>
                  <input required className="w-full p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white"
                    value={formData.serialNumber} onChange={e => setFormData({...formData, serialNumber: e.target.value})} placeholder="CNC..." />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Kat</label>
                  <input required className="w-full p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white"
                    value={formData.floor} onChange={e => setFormData({...formData, floor: e.target.value})} placeholder="4. Kat" />
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Konum / Birim</label>
                <div className="relative">
                   <MapPin size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                   <input required className="w-full pl-10 p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white"
                     value={formData.location} onChange={e => setFormData({...formData, location: e.target.value})} placeholder="Örn: Muhasebe Ofisi" />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Son Sayaç</label>
                  <input type="number" required className="w-full p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white"
                    value={formData.lastCounter} onChange={e => setFormData({...formData, lastCounter: Number(e.target.value)})} />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Uyumlu Toner</label>
                  <input 
                    list="toner-models-list" 
                    className="w-full p-3 border border-slate-200 dark:border-slate-600 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 dark:bg-slate-700 text-slate-900 dark:text-white"
                    value={formData.compatibleToner} 
                    onChange={e => setFormData({...formData, compatibleToner: e.target.value})} 
                    placeholder="Örn: 85A" 
                  />
                  <datalist id="toner-models-list">
                    {config.tonerModels?.map(tm => <option key={tm} value={tm} />)}
                  </datalist>
                </div>
              </div>

              <div className="pt-4 flex gap-3">
                <button type="button" onClick={closeFormModal} className="flex-1 py-4 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors font-semibold">İptal</button>
                <button type="submit" className="flex-1 py-4 bg-primary-600 text-white rounded-xl hover:bg-primary-700 transition-colors font-bold shadow-lg shadow-primary-200 dark:shadow-none">
                  {editingPrinter ? 'Değişiklikleri Kaydet' : 'Cihazı Kaydet'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* History Modal */}
      {isHistoryModalOpen && selectedPrinterHistory && (
         <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-800 rounded-2xl w-full max-w-2xl shadow-2xl overflow-y-auto max-h-[90vh] animate-in slide-in-from-bottom-4 duration-300">
            <div className="bg-white dark:bg-slate-800 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center sticky top-0 z-10">
               <div>
                  <h3 className="font-bold text-xl text-slate-800 dark:text-white">
                    {selectedPrinterHistory.printer.brand} {selectedPrinterHistory.printer.model}
                  </h3>
                  <div className="flex gap-2 items-center mt-1">
                     <span className="bg-primary-50 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 text-xs px-2 py-0.5 rounded font-medium">
                        {selectedPrinterHistory.printer.location}
                     </span>
                     <span className="text-slate-400 text-xs">•</span>
                     <span className="text-slate-500 dark:text-slate-400 text-xs">{selectedPrinterHistory.printer.serialNumber}</span>
                  </div>
               </div>
              <button type="button" onClick={() => setIsHistoryModalOpen(false)} className="p-2 bg-slate-100 dark:bg-slate-700 rounded-full hover:bg-slate-200 transition-colors"><X size={20} className="text-slate-500 dark:text-slate-300" /></button>
            </div>
            
            <div className="p-6">
              <h4 className="font-bold text-slate-800 dark:text-white mb-4 flex items-center gap-2">
                 <div className="p-2 bg-blue-100 dark:bg-blue-900/30 text-blue-600 rounded-lg"><History size={18}/></div>
                 Toner Değişim Geçmişi
              </h4>
              <div className="space-y-4 mb-8">
                {selectedPrinterHistory.tonerLogs.length === 0 && (
                   <div className="text-center py-6 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-dashed border-slate-200 dark:border-slate-700">
                      <p className="text-slate-400">Henüz kayıt yok.</p>
                   </div>
                )}
                {selectedPrinterHistory.tonerLogs.map((log) => (
                    <div key={log.id} className="relative pl-6 border-l-2 border-slate-200 dark:border-slate-700 pb-4 last:pb-0">
                       <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-white dark:bg-slate-800 border-2 border-blue-500"></div>
                       <div className="bg-slate-50 dark:bg-slate-700/50 p-4 rounded-xl border border-slate-100 dark:border-slate-700 hover:shadow-sm transition-shadow">
                          <div className="flex justify-between items-start mb-1">
                             <span className="font-bold text-slate-700 dark:text-slate-200">{log.tonerModel}</span>
                             <span className="text-xs text-slate-400 bg-white dark:bg-slate-800 px-2 py-1 rounded border dark:border-slate-600 shadow-sm">{new Date(log.date).toLocaleDateString('tr-TR')}</span>
                          </div>
                          
                          {/* YIELD DATA - NEW DISPLAY */}
                          {log.pageYield !== undefined && log.pageYield > 0 && (
                             <div className="my-2 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 text-xs px-2 py-1 rounded w-fit font-medium flex items-center gap-1">
                                <History size={10} />
                                Önceki toner verimi: {log.pageYield.toLocaleString()} sayfa
                             </div>
                          )}

                          <p className="text-sm text-slate-500 dark:text-slate-400 mb-2">
                             İşlemi Yapan: <span className="font-medium text-slate-700 dark:text-slate-300">{log.user}</span>
                          </p>
                          {log.description && <p className="text-xs text-slate-400 italic bg-white dark:bg-slate-800 p-2 rounded">{log.description}</p>}
                       </div>
                    </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};