import React, { useState, useEffect } from 'react';
import { StorageService } from '../services/storage';
import { Printer, ServiceRecord, User } from '../types';
import { Wrench, Plus, Save, Clock, CheckCircle2, XCircle } from 'lucide-react';
import { LoadingScreen } from './LoadingScreen';

interface ServiceManagementProps {
  // empty
}

export const ServiceManagement: React.FC<ServiceManagementProps> = () => {
  const [records, setRecords] = useState<ServiceRecord[]>([]);
  const [printers, setPrinters] = useState<Printer[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Form State
  const [selectedPrinterId, setSelectedPrinterId] = useState('');
  const [issue, setIssue] = useState('');
  const [action, setAction] = useState('');
  const [provider, setProvider] = useState('');
  const [cost, setCost] = useState(0);
  const [status, setStatus] = useState<'PENDING' | 'COMPLETED' | 'SCRAPPED'>('PENDING');

  useEffect(() => {
    const fetchData = async () => {
        setLoading(true);
        const r = await StorageService.getServiceRecords();
        const p = await StorageService.getPrinters();
        setRecords(r);
        setPrinters(p);
        setLoading(false);
    };
    fetchData();
  }, []);

  const handlePrinterChange = (printerId: string) => {
    setSelectedPrinterId(printerId);
    const printer = printers.find(p => p.id === printerId);
    if (printer && printer.supplier) {
      setProvider(printer.supplier);
    } else {
      setProvider('');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const printer = printers.find(p => p.id === selectedPrinterId);
    if (!printer) return;

    const newRecord: ServiceRecord = {
      id: '', // Generated by Firestore
      printerId: printer.id,
      printerName: `${printer.brand} ${printer.model} (${printer.location})`,
      date: new Date().toISOString(),
      issue,
      actionTaken: action,
      provider,
      cost,
      status
    };

    await StorageService.addServiceRecord(newRecord);
    
    // Refresh List
    const updatedRecords = await StorageService.getServiceRecords();
    setRecords(updatedRecords);
    
    // Reset Form
    setIssue('');
    setAction('');
    setProvider('');
    setCost(0);
    setStatus('PENDING');
    alert('Servis kaydı eklendi.');
  };

  if (loading) {
    return <LoadingScreen message="Servis kayıtları yükleniyor..." />;
  }

  return (
    <div className="space-y-6">
       <div className="flex flex-col md:flex-row gap-6">
          {/* Form Side */}
          <div className="md:w-1/3 space-y-4">
             <div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700">
                <h3 className="text-lg font-bold text-slate-800 dark:text-white mb-4 flex items-center gap-2">
                   <Wrench size={20} className="text-orange-500"/> Yeni Arıza/Servis Kaydı
                </h3>
                <form onSubmit={handleSubmit} className="space-y-3">
                   <div>
                      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Cihaz Seçimi</label>
                      <select 
                        required
                        className="w-full p-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-orange-500"
                        value={selectedPrinterId}
                        onChange={(e) => handlePrinterChange(e.target.value)}
                      >
                         <option value="">Seçiniz</option>
                         {printers.map(p => (
                           <option key={p.id} value={p.id}>{p.brand} {p.model} - {p.location}</option>
                         ))}
                      </select>
                   </div>
                   
                   <div>
                      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Arıza / Sorun</label>
                      <input 
                         required
                         type="text"
                         className="w-full p-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-orange-500"
                         placeholder="Örn: Kağıt sıkıştırıyor"
                         value={issue}
                         onChange={(e) => setIssue(e.target.value)}
                      />
                   </div>

                   <div>
                      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Yapılan İşlem</label>
                      <textarea 
                         required
                         className="w-full p-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-orange-500"
                         placeholder="Örn: Fuser ünitesi değişti"
                         value={action}
                         onChange={(e) => setAction(e.target.value)}
                         rows={2}
                      />
                   </div>

                   <div className="grid grid-cols-2 gap-3">
                      <div>
                         <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Servis Firması</label>
                         <input 
                           required
                           type="text"
                           className="w-full p-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-orange-500"
                           placeholder="Örn: Yetkili Servis"
                           value={provider}
                           onChange={(e) => setProvider(e.target.value)}
                         />
                      </div>
                      <div>
                         <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Maliyet (TL)</label>
                         <input 
                           type="number"
                           min="0"
                           className="w-full p-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-orange-500"
                           value={cost}
                           onChange={(e) => setCost(Number(e.target.value))}
                         />
                      </div>
                   </div>

                   <div>
                      <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Durum</label>
                      <div className="flex gap-2">
                         <label className="flex items-center gap-1 cursor-pointer bg-slate-100 dark:bg-slate-700 p-2 rounded text-xs">
                           <input type="radio" name="status" checked={status === 'PENDING'} onChange={() => setStatus('PENDING')} /> Bekliyor
                         </label>
                         <label className="flex items-center gap-1 cursor-pointer bg-green-100 dark:bg-green-900/30 p-2 rounded text-xs">
                           <input type="radio" name="status" checked={status === 'COMPLETED'} onChange={() => setStatus('COMPLETED')} /> Tamamlandı
                         </label>
                         <label className="flex items-center gap-1 cursor-pointer bg-red-100 dark:bg-red-900/30 p-2 rounded text-xs">
                           <input type="radio" name="status" checked={status === 'SCRAPPED'} onChange={() => setStatus('SCRAPPED')} /> Hurda/Değişim
                         </label>
                      </div>
                   </div>

                   <button type="submit" className="w-full bg-orange-600 text-white py-3 rounded-lg font-bold hover:bg-orange-700 transition-colors mt-2">
                     Kaydet
                   </button>
                </form>
             </div>
          </div>

          {/* List Side */}
          <div className="flex-1">
             <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-4">Servis Geçmişi</h3>
             <div className="space-y-3">
               {records.length === 0 && <div className="text-slate-400">Henüz servis kaydı bulunmamaktadır.</div>}
               {records.map(record => (
                 <div key={record.id} className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col md:flex-row gap-4 items-start md:items-center justify-between">
                    <div>
                       <div className="flex items-center gap-2 mb-1">
                          <span className={`px-2 py-0.5 rounded text-xs font-bold text-white ${
                             record.status === 'COMPLETED' ? 'bg-green-500' : 
                             record.status === 'PENDING' ? 'bg-yellow-500' : 'bg-red-600'
                          }`}>
                             {record.status === 'COMPLETED' ? 'TAMAMLANDI' : record.status === 'PENDING' ? 'BEKLİYOR' : 'HURDA/DEĞİŞİM'}
                          </span>
                          <span className="text-xs text-slate-400">{new Date(record.date).toLocaleDateString('tr-TR')}</span>
                       </div>
                       <h4 className="font-bold text-slate-800 dark:text-white">{record.printerName}</h4>
                       <p className="text-sm text-red-600 dark:text-red-400 font-medium">Sorun: {record.issue}</p>
                       <p className="text-sm text-slate-600 dark:text-slate-300">İşlem: {record.actionTaken}</p>
                       <p className="text-xs text-slate-400 mt-1">{record.provider}</p>
                    </div>
                    <div className="text-right min-w-[100px]">
                       <p className="text-xs text-slate-500">Maliyet</p>
                       <p className="text-xl font-bold text-slate-800 dark:text-white">{record.cost > 0 ? `${record.cost} ₺` : 'Ücretsiz'}</p>
                    </div>
                 </div>
               ))}
             </div>
          </div>
       </div>
    </div>
  );
};